SQL:
  use-mysql: false
  host: localhost
  port: '3306'
  database: "plugins"
  username: root
  password: 'password'
# this is the prefix that will display on player messages where its needed
prefix: "&#00fff2[DiamondWallet] "
messages:
  mysql-not-connected: "&cdatabase is not connected this feature is disabled"
  not-a-player: "&cYou are not a player"
  player-dont-exist: "&cPlayer Doesnt exist"
  #  %AMOUNT% gives the amount of diamonds that player have these placeholder are Case Sensitive
  walletbal-self: "&a You have %AMOUNT% Diamonds"
  #  %PLAYER% give the player display/nickname
  walletbal-other: "&a %PLAYER% have %AMOUNT% Diamonds"
  wallet-top:
    #   this message will show firsy and have %TOTAL_DIAMONDS% to display total diamonds
    header: "&#ff6f00Top Diamonds List Total diamonds: %TOTAL_DIAMONDS%"
    #    %RANK% is the rank of the player this will get formated as "[#1] shafiahaz2478: 64"
    list: "&#a020f0[#%RANK%] &b%PLAYER%: &e%AMOUNT%"